### ISSUE TITLE
When following the suggested step-through, sample-kinesis-to-timestream-app fails to compile

### ISSUE THREAD

**Issue by eduelias** [awslabs/amazon-timestream-tools#110]
When I clone the repo and run `mvn clean compile`, meeting the required maven/java version, I get this:

<img width="2996" alt="image" src="https://user-images.githubusercontent.com/12836540/172376477-39cd6161-2b9c-4d04-8d61-cf1eaca4344d.png">

```
[ERROR] Failed to execute goal on project sample-kinesis-to-timestream-app: Could not resolve dependencies for project com.amazonaws.samples.connectors.timestream:sample-kinesis-to-timestream-app:jar:0.1-SNAPSHOT: com.amazonaws.samples.connectors.timestream:flink-connector-timestream:jar:0.1-SNAPSHOT was not found in https://repository.apache.org/content/repositories/snapshots/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of apache.snapshots has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

When we look into Maven's [public repo](https://mvnrepository.com/artifact/software.amazon.timestream/flink-connector-timestream/0.1), we see that the dependency is inside this namespace `software.amazon.timestream` but the sample code tries to load from this `com.amazonaws.samples.connectors.timestream` namespace.

Please, update examples with the public repo's data.

**Comment by piotrwest** [comment]
Thanks @eduelias for reporting this. I've fixed the sample to use the Maven repository and updated READMEs. Closing the issue - feel free to reopen in case of any questions.

Thanks, Peter
