### ISSUE TITLE
Question - Using timestream sink with Table API

### ISSUE THREAD

**Issue by andreparodi-bandai** [awslabs/amazon-timestream-tools#126]
Hi,

I am using Kinesis Analytics Studio Notebooks to create some flink application. I would like to process and event stream and create some metrics every minute to send to timestream. Ideally I would like to do that through the Table api of the notebook. 

Is it possible to configure the timestream sink for usage in the ssql interpreter? 
What columns should the table have? 

I haven't been able to find any examples.
Thanks
Andre

**Comment by dkovalenkoI** [comment]
@andreparodi-bandai , is the question still actual? If so, please provide more details regarding the issue you are trying to resolve.  For SQL interpreter it is possible to use [JDBC timestream driver](https://github.com/awslabs/amazon-timestream-driver-jdbc)

**Comment by andreparodi-bandai** [comment]
Hi, I have stopped working on this at present. Thanks for following up. I will close th issue.
