### ISSUE TITLE
Could provide errorMessage of AwsServiceException When handleRetryableException

### ISSUE THREAD

**Issue by chihying7509** [awslabs/amazon-timestream-tools#128]
We got an error message: 
`Retryable 'ValidationException' occurred while inserting to Timestream. Records insertion will be retried. Details: Status Code: 400, Request ID: JU7G6RTRMXNRPHYAVZJ5Z65BQE`
which was thrown from https://github.com/awslabs/amazon-timestream-tools/blob/mainline/integrations/flink_connector/flink-connector-timestream/src/main/java/com/amazonaws/samples/connectors/timestream/DefaultWriteRequestFailureHandler.java#L113-L114

The ValidationException doesn't provide much details for debugging, could you please add `errorMessage` of `AwsServiceException` When executing `handleRetryableException`?

Please let us know if there is a better way to debug TimeStream ValidationException.

Thank you!

**Comment by dkovalenkoI** [comment]
@chihying7509 , The pull request has been created to address the reported issue. 

Thank you for your patience and valuable feedback.
