### ISSUE TITLE
bool('false') also returns True

### ISSUE THREAD

**Issue by SpielerNogard** [awslabs/amazon-timestream-tools#134]
in the sagemaker timestream_query integration, the parser for Boolean uses bool(scalar_value) but this will always return True.
`bool('true') -> True`
`bool('false') -> True`

a better way is to use something like `lambda x : x=='true'`

**Comment by dkovalenkoI** [comment]
@SpielerNogard The pull request has been created to address the reported issue. 

Thank you for your patience and valuable feedback.

**Comment by sethusrinivasan** [comment]
Resolved by https://github.com/awslabs/amazon-timestream-tools/pull/153
