### ISSUE TITLE
Unrecognized resource types: [AWS::Timestream::Table, AWS::Timestream::Database] in region eu-central-1

### ISSUE THREAD

**Issue by robcsi** [awslabs/amazon-timestream-tools#14]
I'm trying to create a template with these resources in region eu-central-1, even when I use the  https://github.com/awslabs/amazon-timestream-tools/blob/master/integrations/iot_core/cfn-iot-rule-to-timestream.json in CloudFormation as described in the integration, but CloudFormation doesn't recognize it.

It is stated in the integration description that only us-east-1 is supported currently.

Is there a planned date when it will also be usable in other regions, than us-east-1?

Thanks

**Comment by robcsi** [comment]
Also, in https://github.com/awslabs/amazon-timestream-tools/blob/master/integrations/iot_core/to-timestream-rule-template.json, JSON elements like "awsIotSqlVersion", "ruleDisabled", etc., need to be upper cased to be correct, when I included the template in the same CF template...
Even so, "timestream" was not recognised neither like "Timestream", nor "TimeStream".

Maybe the aws cli version 2.0.56 accepts them, but CF didn't, even in region us-east-1.

**Comment by psachaamazon** [comment]
Amazon Timestream is currently not available in eu-central-1. That is the reason why the creation of the CloudFormation stack fails. Please use a region where Amazon Timestream is available. 

For your second question is it correct that you trying to create the iot rule with CloudFormation? If yes, the Timestream action is currently not supported in CloudFormation. For a list of supported actions for iot rules in CloudFormation take look at https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iot-topicrule-action.html.

**Comment by robcsi** [comment]
Yes, that is so. Thanks for the info.

I solved this by using the available regions and custom resources with lambda functions to create the rules.
