### ISSUE TITLE
Export cloudwatch metrics to timestream

### ISSUE THREAD

**Issue by jason-riddle** [awslabs/amazon-timestream-tools#16]
I'd like to export cloudwatch metrics to timestream. Mainly to retain metric granularity for longer than what's currently allowed cloudwatch metrics (Metrics Retention Section from https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_concepts.html).

**Comment by tiratatp** [comment]
Hi Jason,

Have you tried sending them via Kinesis Stream?

Here are some docs that might help you,
- https://docs.aws.amazon.com/timestream/latest/developerguide/Kinesis.html
- https://docs.aws.amazon.com/timestream/latest/developerguide/ApacheFlink.html

Best regards,
Tiratat

**Comment by Ulrar** [comment]
Hi,

To be sure - there is no way of streaming cloudwatch metrics into timestream without having to run an application on some instances somewhere ourselves ?
That would have been a great setup, that's unfortunate.

**Comment by danielloader** [comment]
That's a shame, having to run an apache flink stack to move some metrics about seems quite heavy duty.

**Comment by Ulrar** [comment]
So I only realized it too late, but I think what they meant is you can do that through kinesis data analytics, which would be serverless.
Cloudwarch stream -> firehose -> data analytics -> timestream.
Or maybe using a lambda.

Either way it's too late for me, we went a different route, but I'd be interested to know if anyone else gets this working, I do like timestream.
