### ISSUE TITLE
Support for prometheus

### ISSUE THREAD

**Issue by kanishkatn** [awslabs/amazon-timestream-tools#17]
Hi, 

I read in an article that the support for prometheus will be out soon. Are you guys working on an adapter? If yes, may I know the status on it? 

This was mentioned in Prometheus sometime back! https://github.com/prometheus/prometheus/issues/5086

**Comment by tiratatp** [comment]
I saw that Timestream was already listed here: https://prometheus.io/docs/operating/integrations/

Closing since it is not related to this repository.
