### ISSUE TITLE
Amazon timestream in PHP

### ISSUE THREAD

**Issue by uc-asv** [awslabs/amazon-timestream-tools#42]
Please provide a sample code for php. I can't find anywhere about using the amazon timestream in php.  Neither in https://docs.aws.amazon.com/timestream/latest/developerguide/getting-started.java-v1.sample-application.html nor in https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.TimestreamWrite.TimestreamWriteClient.html

Please provide a sample demo for php too or update the docs for PHP too.

**Comment by dkovalenkoI** [comment]
@uc-asv, The pull request has been created to address the reported issue.

Thank you for your patience and valuable feedback.

**Comment by sethusrinivasan** [comment]
@uc-asv, fixed in https://github.com/awslabs/amazon-timestream-tools/pull/161
