### ISSUE TITLE
Sample Application for Timestream is Useless

### ISSUE THREAD

**Issue by robinje** [awslabs/amazon-timestream-tools#44]
The purpose of sample and reference applications is to clearly expose the working mechanisms of your library, in this case the Timestream Client in Boto3. 

What you have built is a demo. Read data from a file and write it to Timestream. All of the useful logic is in 'crud_and_simple_ingestion_example'. Although this is a more professional way of building the code it doesn't fulfill the purpose of the stated purpose of the code.

**Comment by sethusrinivasan** [comment]
Thank you for your feedback. If you are looking for specific code samples, can you provide us more details on the scenarios?

**Comment by cam8001** [comment]
I have written a simple TypeScript utility here to deal with parsing TimeStream queries into usable JS objects: https://gist.github.com/cam8001/44babba44cd912093892589640b96dc5
