### ISSUE TITLE
Hostname incorrect on L4 in query-example for JS example

### ISSUE THREAD

**Issue by ron2911** [awslabs/amazon-timestream-tools#45]
Query is done using this host - https://github.com/awslabs/amazon-timestream-tools/blob/master/sample_apps/js/query-example.js#L4

Inserts are done using this host value - https://github.com/awslabs/amazon-timestream-tools/blob/master/sample_apps/js/crud-and-simple-ingestion-example.js#L224

Wasted time thinking that I am missing something when I was getting empty datasets back. :) 

Please fix this.

**Comment by sethusrinivasan** [comment]
Thank you @ron2911 for reporting this issue. 
Here is PR for the fix:  https://github.com/awslabs/amazon-timestream-tools/pull/46
