### ISSUE TITLE
Unknown parameter in CommonAttributes: "Version", must be one of: Dimensions, MeasureName, MeasureValue, MeasureValueType, Time, TimeUnit

### ISSUE THREAD

**Issue by murphycrosby** [awslabs/amazon-timestream-tools#54]
When running the python sample app for the upsert using the version...I am getting the error:

`Unknown parameter in CommonAttributes: "Version", must be one of: Dimensions, MeasureName, MeasureValue, MeasureValueType, Time, TimeUnit`

**Comment by tiratatp** [comment]
Hi Murphy,

It might be that a SDK that you have is an older version. Could you make sure that when you do `pip3 list` you see a `boto3` version at least 1.6.25?

If you see anything like 1.6.24 or older than you can run `pip3 install -r requirements.txt --upgrade` again to upgrade.

Best regards,
Tiratat

**Comment by murphycrosby** [comment]
Thanks...I'm using the code in a Lambda with python 3.8 using the built in boto3. Looks like the boto3 version: 1.15.16

**Comment by tiratatp** [comment]
Please upgrade to newer Boto3. 😄

**Comment by murphycrosby** [comment]
Thanks @tiratatp. I was confused at first because 1.15.16 is > 1.6.25...but I'm guessing you meant 1.16.25. After doing some testing, it looks like >= 1.16.0 works. Thanks again.

**Comment by murphycrosby** [comment]
However, my lambda is still throwing the error even with the boto3 version.
`START RequestId: 7cf7c524-ded6-4349-9a29-242a2d69b821 Version: $LATEST
boto3 version: 1.16.25
Writing records with upsert
Error: Parameter validation failed:
Unknown parameter in CommonAttributes: "Version", must be one of: Dimensions, MeasureName, MeasureValue, MeasureValueType, Time, TimeUnit
END RequestId: 7cf7c524-ded6-4349-9a29-242a2d69b821
REPORT RequestId: 7cf7c524-ded6-4349-9a29-242a2d69b821	Duration: 4.20 ms	Billed Duration: 5 ms	Memory Size: 128 MB	Max Memory Used: 71 MB	Init Duration: 325.87 ms`

**Comment by jeffrey-cochran** [comment]
I got the same error @murphycrosby

Were you able to resolve this?

**Comment by jeffrey-cochran** [comment]
@tiratatp I can confrim this is still an issue with 1.16.31

**Comment by murphycrosby** [comment]
> I got the same error @murphycrosby
> 
> Were you able to resolve this?

Unfortunately no. I just moved on to Timescaledb.
