### ISSUE TITLE
MaxRows not behaving as expected

### ISSUE THREAD

**Issue by odannyboy000** [awslabs/amazon-timestream-tools#56]
I want to support a pagination feature in my UI that queries timestream. I read that the `MaxRows` property is designed for this, however when I query the data using the MaxRows property, I end up with an empty `Rows` array in the response object. A `NextToken` value is returned, and when used, I get results in subsequent requests.

Here's an example query:

```
const params = {
    QueryString: 'SELECT * FROM "Database"."Table" ORDER BY time DESC LIMIT 1000',
    MaxRows: 5
 };

const response = await timestreamQuery.query(params).promise();
```

The response looks like:

```
{
  "QueryId": "AEBQEAMZYO7AZGV6EIBLJUSHL6PBWIRTIAEGJGC52PFDA7XFAJP6FQCB5YM6NSI",
  "NextToken": "AYABeMHo5Rjm0qIJgttAJJ_7wXEAAAABAAdhd3Mta21zAEthcm46YXdzOmttczp1cy1lYXN0LTE6MzY3NjYxMzk3MDA3OmtleS82NTRiYmIyNy01NzJkLTQwMjQtOWFmMi1mY2NhMTljZDEwMzgAuAECAQB4qkRWblNugHXDCaSOyanYOqmGugUPwIWT4MBR1B0JOyoBup9TKybgy_jT4bDoXMnVgQAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDBY6fQdh9g7SC3XXTgIBEIA7Nai8rNjZZlhIbxDKbKENjpMxY5_Jte6OI4Nztn2fLNCiMIPXIKVX-OpWTZd7tgYe0FSxjAljsuRfU-UCAAAAAAwAABAAAAAAAAAAAAAAAAAAMtu3gCyCNi4u6dpDfpAnJv____8AAAABAAAAAAAAAAAAAAABAAABMPFB9e1v4h7Rpg3UklnipQxygIup1vQEpLjJ8cKi4xENKSjmC",
  "Rows": [
    
  ],
  "ColumnInfo": [
    {
      "Name": "hostname",
      "Type": {
        "ScalarType": "VARCHAR"
      }
    }, // ...berevity
  ],
  "QueryStatus": {
    "ProgressPercentage": 100,
    "CumulativeBytesScanned": 165150,
    "CumulativeBytesMetered": 10000000
  }
}
```

Notice that `Rows` is an empty array. I can use the `NextToken` value to make a subsequent query to get data, but that seemed odd to me that I would have to perform two requests in order to get the first set of data. What am I doing wrong?

**Comment by tiratatp** [comment]
Hi Danny,

This is an expected behavior. Depending on your query's characteristic, Timestream might returns a result set in a paginated manner. See more information in our doc here,

https://docs.aws.amazon.com/timestream/latest/developerguide/code-samples.run-query.html

Basically, you would want to paginate and buffer all data until we don't return the `NextToken` field in the response.

Best regards,
Tiratat

**Comment by tiratatp** [comment]
Oh and also if you have not got a chance to check out our "Best Practices", please do check them out,
https://docs.aws.amazon.com/timestream/latest/developerguide/queries-bp.html
