### ISSUE TITLE
Can't ingest historical data?

### ISSUE THREAD

**Issue by anfreita** [awslabs/amazon-timestream-tools#6]
Hi,

I saw the recent announcement and am excited to evaluate Timestream as a potential replacement for Postgresql+timescaledb in our architecture. I'm not sure if this is the correct place to ask this question so if not please help me find the right place.

I see this in the Best Practices documentation: 

> Ensure that the timestamp of the incoming data is not later than data retention configured for the memory store

And my quick experimentation validates this statement; I'm unable to write any records with a timestamp older than the memory store retention period. Does this mean it's not possible to ingest historical data older than 12 months? This seems to me like a pretty substantial hole and a deal-breaker for migrating any existing applications to Timestream.

Thanks in advance for your response!

**Comment by BastianZim** [comment]
Just to add, feedback from AWS support:

> Therefore unfortunately, ingesting data older than the memory store retention period is not supported. As of now, it's a limitation of the service itself.
> 
> However, this is indeed a valid use case which many customers have been requesting and our service team is working towards bringing this feature to the service.

(I had contacted them about migrating data older than 1 year)

**Comment by tiratatp** [comment]
Thank you for sharing, Bastian. I'll close this issue since it is not an issue with this repository.

**Comment by shirishsurti** [comment]
Unfortunately it's 2023 and still AWS timestream does not support ingesting data older than 12 months!

**Comment by shirishsurti** [comment]
As per this documentation - https://docs.aws.amazon.com/timestream/latest/developerguide/data-ingest.html
Looks like now data older than memory store retention period (12 months while writing this post) can be done by enabling writes on Magnetic store. Just that the data should not be older than magnetic store period.
