### ISSUE TITLE
Unable to load DotNet sample application in Visual Studio

### ISSUE THREAD

**Issue by ninad1103-hub** [awslabs/amazon-timestream-tools#76]
when I try to open .sln file in Visual Studio it says "One or more protests in the solution were not loaded correctly. Please see the output window for details."
![Cap1](https://user-images.githubusercontent.com/75058570/142979682-48481cac-1310-4f5f-a36e-3e2a58e704f7.PNG)
![cap2](https://user-images.githubusercontent.com/75058570/142979690-f86d3924-b63e-468d-87f2-b697971e647c.PNG)

**Comment by sethusrinivasan** [comment]
Thank you for reporting this issue @ninad1103-hub -Pls check if this fix resolves the issue you were seeing
 https://github.com/awslabs/amazon-timestream-tools/commit/12446e96fb4d70a73f313b9ed88078f913067078
