### ISSUE TITLE
Does Amazon Timestream support User Defined Function? 

### ISSUE THREAD

**Issue by AKheli** [awslabs/amazon-timestream-tools#90]
I am currently working on a benchmark of time series database systems for analytical (complex) queries. These queries are algorithms that cannot (easily) be implemented in SQL language so they require a third-party programming language such as C, C++, Python, Java, etc.

I am writing to you to ask if Amazon Timestream supports such a feature of a third-party programming language for User Defined Functions?Does GridDB support User Defined Function

**Comment by charlesjlee** [comment]
Hi @AbdelouahabKhelifati, thank you for your interest in Amazon Timestream. Unfortunately, Timestream does not support user-defined functions.

We do support [many query operators and functions](https://docs.aws.amazon.com/timestream/latest/developerguide/reference.html) including [time series specific functions](https://docs.aws.amazon.com/timestream/latest/developerguide/timeseries-specific-constructs.functions.html) such as interpolation, integration/derivation, correlation, and filter/reduce. With these functions, hopefully it is easier to implement your queries than you anticipated.

**Comment by sethusrinivasan** [comment]
@AbdelouahabKhelifati  - Can you please submit your feature requests via AWS Support - https://console.aws.amazon.com/support/home#/case/create?issueType=technical
