### ISSUE TITLE
UnexpectedParameter "MagneticStoreWriteProperties" in create_table()

### ISSUE THREAD

**Issue by AlphaRalph** [awslabs/amazon-timestream-tools#93]
Independant of the used language, tables can't be created with the "enable magnetic storage writes" set to true.
Python code:
```
session = boto3.Session()
write_client = session.client('timestream-write', config=Config(read_timeout=20, max_pool_connections = 5000, retries={'max_attempts': 10}), region_name='eu-central-1')
retention_properties = {
    "MemoryStoreRetentionPeriodInHours": MEMORY_RETENTION_TIME,
    "MagneticStoreRetentionPeriodInDays": MAGNETIC_RETENTION_TIME
}
magnetic_store_write_properties = {
    "EnableMagneticStoreWrites": True
}
result = write_client.create_table(DatabaseName=DATABASE_NAME, TableName=str(serialNumber),
    MagneticStoreWriteProperties = magnetic_store_write_properties,
    RetentionProperties = retention_properties)
```
Python exception: Unknown parameter in input: "MagneticStoreWriteProperties", must be one of: DatabaseName, TableName, RetentionProperties, Tags

Node.js code:

```
var https = require('https');
var agent = new https.Agent({
    maxSockets: 5000
});

let writeClient = new AWS.TimestreamWrite({
        maxRetries: 10,
        httpOptions: {
            timeout: 20000,
            agent: agent
        }
    }); 

const params = {
        DatabaseName: constants.DATABASE_NAME,
        TableName: event.serialNumber.toString(),
        RetentionProperties: {
            MemoryStoreRetentionPeriodInHours: constants.HT_TTL_HOURS,
            MagneticStoreRetentionPeriodInDays: constants.CT_TTL_DAYS
        },
        MagneticStoreWriteProperties: {
            EnableMagneticStoreWrites: true
        }
    };

const promise = writeClient.createTable(params).promise();
```
Node exception: ERROR	Invoke Error 	{"errorType":"UnexpectedParameter","errorMessage":"Unexpected key 'MagneticStoreWriteProperties' found in params","code":"UnexpectedParameter" ...}

**Comment by sethusrinivasan** [comment]
1) Can you check if you are using latest AWS SDK?
2) Can you run the Javascript code sample  https://github.com/awslabs/amazon-timestream-tools/tree/mainline/sample_apps_reinvent2021/js and see if you facing the same issue?

**Comment by AlphaRalph** [comment]
I'm working directly on aws lambda and figured out, that the default lambda environment (e.g. for python 3.9) has an older sdk version (boto3 1.18.55) preinstalled. After following this guide https://docs.aws.amazon.com/lambda/latest/dg/python-package.html i was able to manually install the latest sdk (in my case boto3 1.20.41) to a local folder, to create a .zip package and upload it to lambda. It worked like a charm.  
Thanks for hint!
