### ISSUE TITLE
Suggestion - For the Java examples, show that the TimeStreamWriteClient is closable

### ISSUE THREAD

**Issue by jkbredsquiggles** [awslabs/amazon-timestream-tools#99]
I created a lambda that writes records to a TimeStream database. I used the examples here as a basis.

My lambda would, under load, throw an EndpointDiscoveryFailedException and somewhere in the stack trace, the following text was in the cause: "unable to create new native thread"

After some poking around, I realized that:
- the lambda's runtime instance was being re-used for multiple requests,
- the TimeStreamWriteClient is autoclosable and needs to be closed in long running applications that create new instances of the client
- I wasn't closing the TimeStreamWriteClient

so, my lambda was running out of resources.

In the examples that I reviewed, in this repository, it appears that NOT closing the client will not cause problems as the application ends. So, it doesn't appear to be a bug.

But, it's a bit sloppy to not close closable resources and people like me use these examples as a basis for their code, so, explicitly closing the client or refactoring to use try with resources, would help neophytes avoid subtle bugs.

And, apologies, if this is not the correct place to offer such suggestions.

**Comment by Gayatri2107** [comment]
I am facing the same issue! How did you close the TimeStreamWriteClient?

**Comment by jkbredsquiggles** [comment]
The TimeStreamWriteClient implements  AutoCloseable. My lambda is in Kotlin, so I used the "use" function, and did something like this:
```
val outerLogger = this.logger
        val outerWriteClient = buildWriteClient(Region.of(environmentProvider.get(TIMESTREAM_REGION_KEY)))!!
        outerWriteClient.use {
            val analyticsService = analyticsServiceBuilder.apply {
                logger = outerLogger
                writeClient = outerWriteClient
                databaseName = environmentProvider.get(TIMESTREAM_DATABASE_KEY)
                tableName = environmentProvider.get(TIMESTREAM_TABLE_KEY)
            }.build()
            val event = AddEvent(command.events.map { it.toService() })
            analyticsService.process(event)
        }

...

Somewhere in the Analytics service, it creates a WriteRecordsRequest and then writes them to TimeStream using the passed in TimeStreamWriteClient, like so:

timestreamWriteClient.writeRecords(request)

```
Where the buildWriteClient function built a TimeStreamWriteClient which was passed to an AnalyticsService. The analyticsService.process(event) method used the client to write to TimeStream and then the 
"use" function closed the TimeStreamWriteClient when it went out of scope.

I think of "use" as Kotlin's try with resources.

For Java, you should be able to use try with resources.  I didn't do it in Java, but I found an example that you should be able to adapt. This is a sample taken from https://www.baeldung.com/java-try-with-resources. 
```
try (Scanner scanner = new Scanner(new File("test.txt"))) {
    while (scanner.hasNext()) {
        System.out.println(scanner.nextLine());
    }
} catch (FileNotFoundException fnfe) {
    fnfe.printStackTrace();
}
```

I hope that helps.

**Comment by sethusrinivasan** [comment]
@jkbredsquiggles Can you please check if the proposed fix https://github.com/awslabs/amazon-timestream-tools/pull/156 addresses the issue you were observing?

**Comment by jkbredsquiggles** [comment]
That looks like it addresses it (with the caveat that my opinion is worth less than it used to be as I don't program in Java much anymore). The comments that were added to the code are also helpful.
